pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=ci/dockercloud
      - status-success=License Compliance
    actions:
      merge:
        method: merge
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=ci/dockercloud
      - status-success=License Compliance
    actions:
      merge:
        method: merge
